spring.application.name=parkease-web
server.port=8080

# Swagger
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

# Service URLs
auth.service.url=http://localhost:8081/api/v1
vehicle.service.url=http://localhost:8086/api/v1
parkinglot.service.url=http://localhost:8082/api/v1
spot.service.url=http://localhost:8083/api/v1
booking.service.url=http://localhost:8084/api/v1
payment.service.url=http://localhost:8085/api/v1
notification.service.url=http://localhost:8087/api/v1
analytics.service.url=http://localhost:8088/api/v1

# Timeouts
spring.mvc.async.request-timeout=30000