spring.application.name=eureka-server
server.port=8761

# Eureka server khud ko register na kare
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

eureka.server.wait-time-in-ms-when-sync-empty=0

# Dashboard
eureka.instance.hostname=localhost
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/